theme: jekyll-theme-hacker

defaults:
-
    scope:
      locale: "en" # To sort by locale. You could also sort by path.
      type: "posts"
    values:
      permalink: :categories/:year/:month/:title/
